import Head from 'next/head'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>What's up clone</title>
        <meta name="description" content="Generated by 20Nov" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />
      
    </div>
  )
}
